# Generated by Django 5.0.6 on 2024-06-16 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pengguna', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='biodata',
            options={'verbose_name_plural': '2. Artikel'},
        ),
        migrations.AddField(
            model_name='biodata',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='pengguna'),
        ),
    ]
