# Generated by Django 5.0.6 on 2024-06-16 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pengguna', '0002_alter_biodata_options_biodata_foto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='biodata',
            options={'verbose_name_plural': '1. Biodata'},
        ),
    ]
